project/project/eshop/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^product/(?P<slug>[-\w]+)/$', views.product_detail, name='product-detail'),
    url(r'^catalog/(?P<slug>[-\w]+)/$', views.product_catalog, name='product-catalog'),
    url(r'^search/',views.search),
    url(r'^cart/add-to-cart/$', views.add_to_cart),
    url(r'^cart/remove-from-cart/$', views.remove_from_cart),
    url(r'^cart/change-count-in-cart/$', views.change_count_in_cart),
    url(r'^cart/$', views.cart),
]

handler404 = views.error404

project/project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('project.eshop.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

for comp_url in settings.COMPONENTS:
    urlpatterns += static(comp_url, document_root=settings.COMPONENTS[comp_url])

project/project/eshop/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib import admin
from django.urls import reverse
from .fields import ThumbnailImageField


class CatalogTop(models.Model):
    title = models.CharField(max_length=50)
    order = models.IntegerField()
    slug = models.SlugField()

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return ''

    class Meta:
        ordering = ['order']


class CatalogSub(models.Model):
    title = models.CharField(max_length=50)
    order = models.IntegerField()
    slug = models.SlugField()
    parent = models.ForeignKey(CatalogTop)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product-catalog', args=(self.slug,))

    class Meta:
        ordering = ['order']


class CatalogSubInLine(admin.StackedInline):
    model = CatalogSub
    prepopulated_fields = {'slug': ('title',)}


class CatalogSubAdmin(admin.ModelAdmin):
    prepopulated_fields = {'slug': ('title',)}


class CatalogTopAdmin(admin.ModelAdmin):
    inlines = [CatalogSubInLine]
    prepopulated_fields = {'slug': ('title',)}


class Product(models.Model):
    title = models.CharField(max_length=250, blank=False)
    slug = models.SlugField()
    code = models.CharField(max_length=10)
    price = models.DecimalField(max_digits=18, decimal_places=2)
    catalog = models.ForeignKey(CatalogSub)
    description = models.TextField()

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product-detail', args=(self.slug,))

    def get_formated_price(self):
        return '{:.0f}'.format(self.price)

class ProductPhoto(models.Model):
    product = models.ForeignKey(Product)
    image = ThumbnailImageField(
        upload_to='product_photos',
        thumb_width=200,
        thumb_height=180
    )
    order = models.IntegerField()

    class Meta:
        ordering = ['order']

    def __unicode__(self):
        return str(self.id)

    def get_absolute_url(selfs):
        return 'product-photo'  # reverse('product-photo', args=(selfs.id,))


class ProductPhotoInLine(admin.StackedInline):
    model = ProductPhoto


class ProductAdmin(admin.ModelAdmin):
    prepopulated_fields = {'slug': ('title',)}
    inlines = [ProductPhotoInLine]


class FilterManager(models.Manager):
    def user_id(self, id):
        return super(FilterManager, self).get_queryset().filter(user_id=id)


class Cart(models.Model):
    user_id = models.CharField(max_length=100)
    product = models.ForeignKey(Product)
    count = models.IntegerField(default=0)
    price = models.DecimalField(default=0, max_digits=18, decimal_places=2)
    summ =  models.DecimalField(default=0, max_digits=18, decimal_places=2)

    filters = FilterManager()
    objects = models.Manager()

    def save(self, *args, **kwargs):
        self.summ = self.price * self.count
        super(Cart, self).save(*args, **kwargs)

admin.site.register(Cart)
admin.site.register(Product, ProductAdmin)
admin.site.register(CatalogTop, CatalogTopAdmin)
admin.site.register(CatalogSub, CatalogSubAdmin)

project/project/eshop/views.py
import json, uuid
from decimal import Decimal
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.db.models import Q
from django.core import serializers
from django.http import Http404
from .models import Product, CatalogTop, CatalogSub, Cart


def get_session_data(session):
    user_id=session.get('user_id', None)
    if not user_id:
        session['user_id'] = str(uuid.uuid1())
    session.modified = True
    return {'user_id': session['user_id']}


def get_paginator_builder(_count, _current):

    MAX_SIZE=9

    result=[]
    if _count > MAX_SIZE:
        c_range=[_current]
        l_sp=False
        r_sp=False
        if _current > 5:
            l_sp=True
            l_range=[1]
            l_range.append('.')
        else:
            l_range=range(1,_current)

        if (_count-_current) >= 5:
            r_sp=True
            r_range=['.']
            r_range.append(_count)
        else:
            r_range=range(_current+1, _count+1)

        if l_sp and r_sp:
            l_range.append(_current-2)
            l_range.append(_current-1)
            r_range.insert(0,_current+1)
            r_range.insert(0,_current+2)
        elif not l_sp and r_sp:
            r_=range(_current+1,_current+1+MAX_SIZE-(len(l_range)+len(c_range)+len(r_range)))
            r_.extend(r_range)
            r_range=r_
        elif not r_sp and l_sp:
            l_=range(_current-(MAX_SIZE-(len(l_range)+len(c_range)+len(r_range))), _current)
            l_range.extend(l_)

        result.extend(l_range)
        result.extend(c_range)
        result.extend(r_range)
    else:
        result=range(1,_count+1)

    return result


def get_fields_from_json(json_data, fields):
    dict = {}
    for i in fields:
        try:
            dict[i] = json_data[i]
        except KeyError:
            dict[i] = None
    return dict


def get_cart_preview(cart):
    dict = {'count':0, 'summ_total':0, 'empty': True}
    for c in cart:
        dict['count'] = dict['count'] + c.count
        dict['summ_total'] = dict['summ_total'] + c.summ

    dict['summ_total'] = '{:.0f}'.format(dict['summ_total'])
    dict['empty'] = dict['count'] == 0
    return dict


def create_template_args(request):
    session_data = get_session_data(request.session)
    cart = Cart.filters.user_id(session_data['user_id'])
    args = {'cart_preview': get_cart_preview(cart),
            'session_data': session_data,}
    return args


#views

def home(request):
    args = create_template_args(request)
    args['product_list'] = Product.objects.all()
    args['catalog_menu'] = CatalogTop.objects.all()
    return render(request, 'home.html', args)


def product_detail(request, slug):
    args = create_template_args(request)
    product = get_object_or_404(Product, slug=slug)
    args['product_detail'] = product
    args['product_in_cart'] = Cart.objects.filter(Q(user_id = args['session_data']['user_id']) & Q(product = product))
    return render(request, 'product_detail.html', args)


def product_catalog(request, slug):
    sub_catalog = get_object_or_404(CatalogSub, slug=slug)
    product_list = Product.objects.filter(catalog = sub_catalog)

    paginator = Paginator(product_list, 5)
    page = request.GET.get('page')
    try:
        product_list = paginator.page(page)
    except PageNotAnInteger:
        #If page not an integer, deliver first page.
        product_list = paginator.page(1)
    except EmptyPage:
        #If page out of range, deliver last page.
        product_list = paginator.page(paginator.num_pages)
    paginator_builder = get_paginator_builder(product_list.paginator.num_pages, product_list.number)

    args = create_template_args(request)
    args['product_list'] = product_list
    args['catalog_menu'] = CatalogTop.objects.all()
    args['sub_catalog'] = sub_catalog
    args['paginator_builder'] = paginator_builder
    return render(request, 'product_catalog.html', args)


def cart(request):
    session_data = get_session_data(request.session)
    args = create_template_args(request)
    args['cart'] = []
    for cart in Cart.filters.user_id(session_data['user_id']):
        args['cart'].append({
            'summ' : '{:.0f}'.format(cart.product.price * cart.count),
            'price' :'{:.0f}'.format(cart.price),
            'count' :cart.count,
            'product_id' : cart.product.id,
            'title' : cart.product.title,
            'product' : cart.product,
        })
    return render(request, 'cart.html', args)


@csrf_exempt
def add_to_cart(request):
    session_data=get_session_data(request.session)
    if request.method == 'POST':
        json_data = get_fields_from_json(json.loads(request.body),['product_id','count'])
        product = get_object_or_404(Product, id=json_data['product_id'])

        if product and session_data['user_id'] and json_data['count']:
            carts = Cart.objects.filter(Q(user_id = session_data['user_id']) & Q(product = product))
            if carts:
                cart = carts[0]
            else:
                cart = Cart()

            cart.product = product
            cart.count = cart.count + int(json_data['count'])
            cart.price = product.price
            cart.user_id = session_data['user_id']
            cart.save()
        else:
            raise Http404 #error 404

    json_text = json.dumps(create_template_args(request)['cart_preview'])
    response = HttpResponse()
    response['Content-Type'] = 'application/json; charset=utf-8'
    response.write(json_text)
    return response


@csrf_exempt
def remove_from_cart(request):
    session_data=get_session_data(request.session)
    if request.method == 'POST':
        json_data = get_fields_from_json(json.loads(request.body),['product_id'])
        product = get_object_or_404(Product, id=json_data['product_id'])

        if product and session_data['user_id']:
            carts = Cart.objects.filter(Q(user_id = session_data['user_id']) & Q(product = product))
            if carts:
                carts[0].delete()
            else:
                raise Http404 #error 404
        else:
            raise Http404 # error 404

    json_text = json.dumps(create_template_args(request)['cart_preview'])
    response = HttpResponse()
    response['Content-Type'] = 'application/json; charset=utf-8'
    response.write(json_text)
    return response


@csrf_exempt
def change_count_in_cart(request):
    session_data = get_session_data(request.session)

    if request.method == 'POST':
        json_data = get_fields_from_json(json.loads(request.body),['product_id', 'count'])
        product = get_object_or_404(Product, id=json_data['product_id'])

        if product and session_data['user_id'] and json_data['count']:
            carts = Cart.objects.filter(Q(user_id=session_data['user_id']) & Q(product=product))
            if carts:
                carts[0].count = json_data['count']
                carts[0].save()
            else:
                raise Http404 #error 404
        else:
            raise Http404 #error 404

    args = create_template_args(request)
    args['cart_preview']['summ'] = '{:.0f}'.format(product.price * json_data['count'])
    args['cart_preview']['price'] = product.get_formated_price()
    args['cart_preview']['product_id'] = product.id
    args['cart_preview']['title'] = product.title
    json_text = json.dumps(args['cart_preview'])
    response = HttpResponse()
    response['Content-Type'] = 'application/json; charset=utf-8'
    response.write(json_text)
    return response


def search(request):
    if request.method == 'GET':
        term = request.GET.get('q')
        product_list = Product.objects.filter(Q(title__contains = term) | Q(description__contains = term))

        paginator = Paginator(product_list, 5)
        page = request.GET.get('page')
        try:
            product_list = paginator.page(page)
        except PageNotAnInteger:
            # If page not an integer, deliver first page.
            product_list = paginator.page(1)
        except EmptyPage:
            # If page out of range, deliver last page.
            product_list = paginator.page(paginator.num_pages)
        paginator_builder = get_paginator_builder(product_list.paginator.num_pages, product_list.number)

        args = create_template_args(request)
        args['product_list'] = product_list
        args['catalog_menu'] = CatalogTop.objects.all()
        args['paginator_builder'] = paginator_builder
        args['term'] = term
        return render(request, 'search.html', args)
    else:
        raise Http404 #error 404


def error404(request):
    return render(request, 'error404.html')

project/project/eshop/templates/components/catalog_menu.html
<!--
parameters:
    catalog_menu
    sub_catalog
-->
<!-- Start. catalog menu -->
<div class="catalog-menu">
<div class="description"><span>КАТАЛОГ</span></div> 
    {% for top in catalog_menu %}          
        <!-- Start. catalog top -->
        <div class="menu-item" data-href="">
            <div class="category"><span>{{top.title}}</span></div>
            
            {% if sub_catalog.parent.id == top.id %}
            <div class="active"><img class="arrow" src="/img/arrow-down.png" alt="" ></div>
            {% else %}
            <div class="active"><img class="arrow" src="/img/arrow-left.png" alt="" ></div>
            {% endif %}
        </div>
        <!-- End. catalog top -->
        {% if top.catalogsub_set.count %}
            
            {% if sub_catalog.parent.id == top.id %}
            <div class="sub-menu sub-menu-open">
            {% else %}
            <div class="sub-menu">
            {% endif %}
            
            {% for sub in top.catalogsub_set.all %}                 
                <!-- Start. catalog sub -->
                <div class="sub-menu-item">
                    <a href="{{sub.get_absolute_url}}">
                        <div class="sub-active"></div>
                        {% if sub_catalog.id == sub.id %}
                        <div class="sub-category sub-category-open">{{sub.title}}</div>
                        {% else %}
                        <div class="sub-category">{{sub.title}}</div>
                        {% endif %}
                    </a>
                </div>
                <!-- End. catalog sub -->                  
            {% endfor %}              
            </div>
        {% endif %}       
    {% endfor %}    
</div>
<!-- End. catalog menu -->

project/project/eshop/templates/components/paginator.html
<!--
parameters:
    product_list
    paginator_builder , see get_paginator_builder()
-->
<!-- Start. pagenator -->
<div class="page-switcher-holder">
    <div class="page-switcher">                   
        
        {% if product_list.has_previous %}
            <a href="?page={{product_list.previous_page_number}}">
            <div class="page-number">
                <img src="/img/prev-page.png" alt="" >
            </div>    
            </a>
        {% else %}    
            <div class="page-number-disable">
                <img src="/img/prev-page.png" alt="" >
            </div>
        {% endif %}
        
        {% for page in paginator_builder%} 
            {% if page == '.' %}
                <div class="page-spacer">...</div>
            {% elif page == product_list.number %}
                <a href="?page={{page}}">
                    <div class="page-number current-page"> {{page}}</div>
                </a>
            {% else %}
                <a href="?page={{page}}">
                    <div class="page-number">{{page}}</div>
                </a>
            {% endif %}    
        {% endfor %}
        
        {% if product_list.has_next %}
            <a href="?page={{product_list.next_page_number}}">
                <div class="page-number">
                    <img src="/img/next-page.png" alt="" >
            </div>
           </a>     
        {% else %}
            <div class="page-number-disable">
                <img src="/img/next-page.png" alt="" >
           </div>
        {% endif %}
        
    </div>
</div>
<!-- End. pagenator -->
 

project/project/eshop/templates/components/product_list.html
<!--
parameters:
    product_list
-->
<!-- Start. product-list -->
<div class="goods-list">
{% for product in product_list %}
    <div class="good" id="{{product.id}}">
        <a href="{{product.get_absolute_url}}" >
            <img class="main-image" id="product_image_{{product.id}}" src="{{product.productphoto_set.all.0.image.thumb_url}}" alt="" >
            <div>
                <div class="description" id="product_description_{{product.id}}">{{product.title}}</div>
            </div>
        </a>
        <div class="buy-container">
            <div class="price">
                <span><b>{{product.get_formated_price}} грн</b></span>
            </div>
            <div class="button-buy">Купить</div>
        </div>
    </div>
{% endfor %}    
</div>
<!-- End. product-list -->
 